Mission4_rb585/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4_rb585.Models
{
    public class GradeCalcModel
    {
        [Required]
        [Range (0, 100, ErrorMessage ="Please enter a number between 0 and 100")]
        public int Assign { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public int Group { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public int Quiz { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public int Midterm { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public int Final { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public int Intex { get; set; }
    }
}

Mission4_rb585/Controllers/Mission5Controller.cs
using Microsoft.AspNetCore.Mvc;
using Mission4_rb585.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4_rb585.Controllers
{
    public class Mission5Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalc()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalc(GradeCalcModel model)
        {
            return View();
        }
    }
}

Mission4_rb585/Views/Mission5/GradeCalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model GradeCalcModel;

<!--Grade Form-->
<h2>Grade Calculator</h2>
<form method="post">
    <fieldset>
        <label>Assignments</label>
        <input id="AGrade" asp-for="Assign"/><br />
        <label>Group Project</label>
        <input id="GPGrade" asp-for="Group"/><br />
        <label>Quizzes</label>
        <input id="QGrade" asp-for="Quiz"/><br />
        <label>Midterm Exam</label>
        <input id="MEGrade" asp-for="Midterm"/><br />
        <label>Final Exam</label>
        <input id="FEGrade" asp-for="Final"/><br />
        <label>INTEX</label>
        <input id="IGrade" asp-for="Intex"/><br />
        <input type="submit" id="btnCalc" value="Calculate Grade" />
        <h3><span id="LetterGrade"></span></h3>
        <div asp-validation-summary="All"></div>
    </fieldset>
</form>

Mission4_rb585/Views/Mission5/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "About Raygen Blackwell";
}
    
<h1>Raygen Blackwell</h1>

    <p>I hope to be able to learn how to use VS Community as well as how to code in C# and use ASP.NET</p>

    <img src="img/IMG_4004.JPEG" height="500" />

    <!--Jobs List-->
    <p>Top Three jobs I want to pursue: </p>
    <ul>
        <li>Flower Picker</li>
        <li>Baker</li>
        <li>Quality Assurance Engineer</li>
    </ul>

Mission4_rb585/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="../wwwroot/img/flower icon.png" type="image/icon type">
    <link href="../wwwroot/css/StyleSheet.css" rel="stylesheet" />
    <link href="../wwwroot/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="Mission5" asp-action="Index">Home</a>
        <a asp-controller="Mission5" asp-action="GradeCalc">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="../wwwroot/bootstrap/js/bootstrap.min.js"></script>
    <script src="../wwwroot/lib/jQuery/jquery-3.6.3.min.js"></script>
    <script src="../wwwroot/jsfiles/GradeCalculator.js"></script>
</body>
</html>